### ISSUE TITLE
Timetable

### ISSUE THREAD

**Issue by budde377** [laundree/app#5]
Add timetable scene for booking and viewing bookings

**Comment by budde377** [comment]
![appdesign - timetable-01](https://cloud.githubusercontent.com/assets/3490507/22626754/3711539e-ebb5-11e6-83ba-bc1fb9722b65.png)

**Comment by malenesoeholm** [comment]
- [ ] Display new day by navigating with arrows (maybe not later than today)
- [ ] Scroll to current time
- [ ] Show current time
- [ ] Grey out unbookable slots (i.e. too late to book)
- [ ] Able to book slots
- [ ] Able to delete booking slots
- [ ] Rules for time
- [ ] Grey out slots for broken machines

**Comment by malenesoeholm** [comment]
Created new issue #21 for unsolved point in checklist.

**Comment by malenesoeholm** [comment]
Created new issue #22 for unsolved point in checklist.
